//
//  MainPresenter.swift
//  RSR-V2
//
//  Created by Ehsan on 20/09/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  For more information visit: http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
  func presentSomething(response: Main.Something.Response)
}

class MainPresenter: MainPresentationLogic {
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Main.Something.Response) {
    let viewModel = Main.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
